
export const ACTION_REMOVE_BOOK = "ACTION_REMOVE_BOOK";
export const ACTION_UPDATE_BOOK = "ACTION_UPDATE_BOOK";
export const ACTION_ADD_BOOK = "ACTION_ADD_BOOK";
export const ACTION_SET_ACTIVE_BOOK = "ACTION_SET_ACTIVE_BOOK";
